### ISSUE TITLE
Readme.md file for each solution

### ISSUE THREAD

**Issue by banerjeesoumya15** [Susmita-Dey/HackerRank-Python-Solutions#1]
Separate folders could be created for each solution, and readme.md file could be created to explain question as well as the proposed solution

**Comment by Susmita-Dey** [comment]
Ok make it. Do you want this issue to be assigned?

**Comment by banerjeesoumya15** [comment]
Sure, you can assign it to me.

**Comment by banerjeesoumya15** [comment]
FIXED and merged
